/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Cw20Base.types";
import * as _1 from "./Cw20Base.client";
import * as _2 from "./Cw20Base.react-query";
export namespace contracts {
  export const Cw20Base = { ..._0,
    ..._1,
    ..._2
  };
}
export * from "./types";